### PR TITLE
Adding main.nf and nextflow.config

### PR DESCRIPTION
**Pull request by sharma-shruti**
Nextflow wrapper for create CSV function

### CODE REVIEW

**Review by abhi18av — CHANGES_REQUESTED** [review]
Apart from the `nextflow.config` and `docker` issue - it looks good to merge.

Also, please try to add a GIF for running this on atleast 3 csv files as a good PR documentation practice.

**Review by abhi18av — DISMISSED** [review]
LGTM

**Review by abhi18av — CHANGES_REQUESTED** [review]
I'll approve once you've tested this on a local computer and attach GIF as a proof of the user experience 😉

**Review by abhi18av — CHANGES_REQUESTED** [review]
@sharma-shruti 
As we discussed over the call, the GIF is only meant to be added to the PR comments for improved understanding of the reviewer.

**Comment by sharma-shruti** [comment]
Here's the GIF

**Comment by abhi18av** [comment]
@sharma-shruti , awesome 🚀

**Comment by abhi18av** [comment]
Let me know when you'd like me merge :)

**Comment by abhi18av** [comment]
Please release a version - I've merged already.

**Pull request merged**
